config-version: 2

name: 'github_source'
version: '0.2.1'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  github_source:
    +schema: staging
    +materialized: table
    tmp:
      +materialized: ephemeral
